# Generated by Django 2.2.3 on 2019-07-14 10:16

import core.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('number', models.IntegerField(verbose_name='number')),
                ('part', models.IntegerField(verbose_name='part')),
                ('deadline', models.DateTimeField(verbose_name='deadline')),
                ('file', models.FileField(upload_to='assignments/', verbose_name='file')),
                ('solution_file_type', models.CharField(max_length=100, verbose_name='solution_file_type')),
            ],
            options={
                'unique_together': {('number', 'part')},
            },
        ),
        migrations.CreateModel(
            name='StudentAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_on', models.DateTimeField(blank=True, verbose_name='submitted_on')),
                ('submission_count', models.IntegerField(blank=True, default=0, verbose_name='submission_count')),
                ('penalty', models.FloatField(blank=True, default=0, verbose_name='penalty')),
                ('solution_file', models.FileField(upload_to=core.models.filenamer, verbose_name='solution_file')),
                ('need_late_days', models.BooleanField(default=False, verbose_name='need_late_days')),
                ('late_days_used', models.DurationField(default=datetime.timedelta(0), verbose_name='late_days_count')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment', to='core.Assignment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'assignment', 'submitted_on')},
            },
        ),
    ]
