"""
Django settings for autograder project.

Generated by 'django-admin startproject' using Django 2.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os
from decouple import config,Csv

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = 'zzt+!$t72vejc55c(_qna7sjn=ksqc86_*w%8&o01kxh0=2*&y'
SECRET_KEY = config('SECRET_KEY')
# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = False
DEBUG = config('DEBUG',default=False,cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS',cast=Csv())


# Application definition

INSTALLED_APPS = [
    'accounts.apps.AccountsConfig',
    'core.apps.CoreConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = config('ROOT_URLCONF')

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': config('TEMPLATES_DIRS', cast=lambda v: [os.path.join(BASE_DIR,s.strip()) for s in v.split(',')],default=[os.path.join(BASE_DIR,'templates')]),
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = config('WSGI_APPLICATION')


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases


DATABASES = {
    'default': {
        'ENGINE': config('DB_ENGINE',default='django.db.backends.postgresql_psycopg2'),
        'NAME':config('DB_NAME',default=''),
        'HOST':config('DB_HOST',default=''),
        'PORT':config('DB_PORT',default='5432'),
        'USER':config('DB_USER'),
        'PASSWORD':config('DB_PASSWORD'),
       
    }
}



# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = config('STATIC_URL',default='/static/')

STATICFILES_DIRS = config('STATICFILES_DIRS', cast=lambda v: [os.path.join(BASE_DIR,s.strip()) for s in v.split(',')],default=[os.path.join(BASE_DIR,'assets')])
STATIC_ROOT=os.path.join(BASE_DIR,config('STATIC_ROOT',default='static'))


MEDIA_ROOT=os.path.join(BASE_DIR, config('MEDIA_ROOT',default='media'))
MEDIA_URL=config('MEDIA_URL',default='/files/')

LOGIN_REDIRECT_URL=config('LOGIN_REDIRECT_URL',default='dashboard')
LOGOUT_REDIRECT_URL=config('LOGOUT_REDIRECT_URL',default='login')
ACCOUNT_AUTHENTICATED_LOGIN_REDIRECTS = config('ACCOUNT_AUTHENTICATED_LOGIN_REDIRECTS',cast=bool,default=True)
AUTH_USER_MODEL=config('AUTH_USER_MODEL',default='accounts.User')

# 2.5MB - 2621440
# 5MB - 5242880
# 10MB - 10485760
# 20MB - 20971520
# 50MB - 52428800
# 100MB 104857600
# 250MB - 214958080
# 500MB - 429916160
MAX_UPLOAD_SIZE = config('MAX_UPLOAD_SIZE',default='5242880')

PROTECTED_MEDIA_URL = config('PROTECTED_MEDIA_URL',default='/protected/')
PROTECTED_MEDIA_ROOT = os.path.join(BASE_DIR,config('PROTECTED_MEDIA_ROOT',default='protected'))
PROTECTED_MEDIA_LOCATION_PREFIX=config('PROTECTED_MEDIA_LOCATION_PREFIX',default='/internal')
PROTECTED_MEDIA_SERVER = config('PROTECTED_MEDIA_SERVER',default='nginx')
PROTECTED_MEDIA_AS_DOWNLOADS = config('PROTECTED_MEDIA_AS_DOWNLOADS',cast=bool,default=False)
